"""Bilingual search: expand English query terms to Latvian equivalents before matching.

Expansion runs before token scoring and does not change fingerprint logic.
Lookup is case-insensitive and diacritics-insensitive (via normalize_text).
"""

from __future__ import annotations

from app.services.normalize import normalize_text, tokenize

# Phrase (normalized, lowercase) -> extra terms to add for matching.
PHRASE_SYNONYMS: dict[str, list[str]] = {
    # ── dairy / cheese varieties ──
    "red lentils": ["sarkanas lēcas"],
    "greek yogurt": ["grieķu jogurts"],
    "greek yoghurt": ["grieķu jogurts"],
    "cottage cheese": ["biezpiens"],
    "cream cheese": ["krēmsiers"],
    "sour cream": ["krējums"],
    "whipped cream": ["putukrējums"],
    "gouda cheese": ["gouda siers"],
    "feta cheese": ["feta siers"],
    "cheddar cheese": ["čedaras siers", "cheddar"],
    "mozzarella cheese": ["mocarella", "mozzarella"],
    "parmesan cheese": ["parmezāns", "parmezan"],
    "brie cheese": ["brī siers", "brie"],
    "processed cheese": ["kausētais siers", "kausēts siers"],
    "blue cheese": ["zilais siers", "zilā pelējuma siers"],
    # ── oils ──
    "olive oil": ["olīveļļa", "eļļa"],
    "sunflower oil": ["saulespuķu eļļa"],
    "coconut oil": ["kokosriekstu eļļa"],
    "rapeseed oil": ["rapšu eļļa"],
    # ── bakery ──
    "wholewheat toast": ["pilngraudu tostermaize", "pilngraudu toast"],
    "whole wheat toast": ["pilngraudu tostermaize", "pilngraudu toast"],
    "whole wheat bread": ["pilngraudu maize"],
    "wholewheat bread": ["pilngraudu maize"],
    "white bread": ["baltmaize"],
    "rye bread": ["rudzu maize", "rupjmaize"],
    "sliced bread": ["sagriezta maize"],
    "toast bread": ["tostermaize", "toast maize", "toastmaize"],
    # ── meat ──
    "ground meat": ["malta gaļa"],
    "minced meat": ["malta gaļa"],
    "chicken breast": ["vistas krūtiņa", "vistas fileja"],
    "chicken fillet": ["vistas fileja"],
    "pork chop": ["cūkgaļas karbonāde"],
    "pork tenderloin": ["cūkgaļas muguras fileja"],
    # ── drinks ──
    "orange juice": ["apelsīnu sula"],
    "apple juice": ["ābolu sula"],
    "sparkling water": ["gāzēts ūdens"],
    "mineral water": ["minerālūdens"],
    "ice cream": ["saldējums"],
    # ── household ──
    "dish soap": ["trauku mazgāšanas līdzeklis", "trauku", "mazgāšanas"],
    "toilet paper": ["tualetes papīrs"],
    "washing powder": ["veļas pulveris"],
    "laundry detergent": ["veļas mazgāšanas līdzeklis", "veļas"],
    "fabric softener": ["veļas mīkstinātājs", "mīkstinātājs"],
    "dishwasher tablets": ["trauku mazgājamās mašīnas tabletes"],
    "paper towels": ["papīra dvieļi"],
    # ── snacks / misc ──
    "peanut butter": ["zemesriekstu sviests", "zemesriekstu krēms"],
    "dark chocolate": ["tumšā šokolāde"],
    "milk chocolate": ["piena šokolāde"],
    "energy drink": ["enerģijas dzēriens"],
    "protein bar": ["proteīna batoniņš", "olbaltumvielu batoniņš"],
    # ── Latvian phrases ──
    "pilngraudu maize": ["pilngraudu maize", "whole wheat bread"],
    "pilngraudu tostermaize": ["pilngraudu tostermaize", "wholewheat toast"],
    "rudzu maize": ["rudzu maize", "rupjmaize"],
    "auzu parslas": ["auzu pārslas", "oatmeal"],
    "auzu putra": ["auzu pārslas", "putra", "oatmeal"],
    "malta gala": ["malta gaļa"],
    "maltas galas": ["malta gaļa"],
    "vistas fileja": ["vistas fileja", "chicken fillet"],
    "vistas krutina": ["vistas krūtiņa", "chicken breast"],
    "cukas gala": ["cūkgaļa", "cūkas"],
    "liellopa gala": ["liellopa gaļa"],
    "zobu pasta": ["zobu pasta", "toothpaste"],
    "velas pulveris": ["veļas pulveris", "laundry"],
    "tualetes papirs": ["tualetes papīrs", "toilet paper"],
    "trauku mazgasanas": ["trauku mazgāšanas līdzeklis", "dish soap"],
    "velas mikstinatajs": ["veļas mīkstinātājs", "fabric softener"],
    "gouda siers": ["gouda siers", "gouda"],
    "feta siers": ["feta siers", "feta"],
    "kausetas siers": ["kausētais siers"],
    "kausetais siers": ["kausētais siers"],
    "skabais krejums": ["skābais krējums"],
    "gazetsudens": ["gāzēts ūdens"],
    "gazets udens": ["gāzēts ūdens", "sparkling water"],
    "mineraludens": ["minerālūdens"],
    "apelsinu sula": ["apelsīnu sula"],
    "abolu sula": ["ābolu sula"],
    "saulespuku ella": ["saulespuķu eļļa", "sunflower oil"],
    "olivella": ["olīveļļa"],
    "rapsu ella": ["rapšu eļļa"],
    "kokosriekstu ella": ["kokosriekstu eļļa"],
    "piena sokolade": ["piena šokolāde"],
    "tumsa sokolade": ["tumšā šokolāde"],
    "sarkanas lecas": ["sarkanas lēcas"],
    "grieķu jogurts": ["grieķu jogurts"],
    "grieku jogurts": ["grieķu jogurts"],
}

# English (normalized lowercase) -> Latvian terms to add to the query.
# Short/partial forms also map to full terms for prefix matching.
search_synonyms: dict[str, list[str]] = {
    # ── dairy ──
    "milk": ["piens"],
    "butter": ["sviests"],
    "cheese": ["siers"],
    "yogurt": ["jogurts"],
    "yogurts": ["jogurts"],
    "yoghurt": ["jogurts"],
    "cream": ["krējums"],
    "kefir": ["kefīrs"],
    "curd": ["biezpiens"],
    "curds": ["biezpiens"],
    # ── cheese varieties (international names used in LV titles) ──
    "gouda": ["gouda"],
    "feta": ["feta"],
    "cheddar": ["cheddar", "čedars"],
    "mozzarella": ["mocarella", "mozzarella"],
    "parmesan": ["parmezāns", "parmezan"],
    "brie": ["brie", "brī"],
    "camembert": ["camembert", "kamambērs"],
    "mascarpone": ["mascarpone", "maskarpone"],
    "ricotta": ["ricotta", "rikotta"],
    "emmental": ["emmental", "ementāles"],
    "edam": ["edam"],
    "tilsit": ["tilžas", "tilzītes"],
    "roquefort": ["rokfors"],
    "halloumi": ["halloumi", "halumi"],
    # ── eggs ──
    "eggs": ["olas"],
    "egg": ["olas"],
    # ── bread / bakery ──
    "bread": ["maize"],
    "baguette": ["bagete"],
    "toast": ["tostermaize", "toast", "toastmaize"],
    "toasts": ["tostermaize", "toast"],
    "wholewheat": ["pilngraudu"],
    "wholegrain": ["pilngraudu"],
    "wholemeal": ["pilngraudu"],
    "sourdough": ["skābmaize", "ieraugu"],
    "croissant": ["kruasāns", "kruasans"],
    "roll": ["maizīte"],
    "rolls": ["maizītes"],
    "bun": ["bulciņa"],
    "buns": ["bulciņas"],
    "tortilla": ["tortilla", "tortiljas"],
    "pita": ["pita", "pitas"],
    "crispbread": ["sausiņi", "knekmaize"],
    # ── cereals / breakfast ──
    "oats": ["auzu pārslas", "auzu"],
    "oatmeal": ["auzu pārslas", "auzu"],
    "porridge": ["putra", "auzu pārslas"],
    "muesli": ["musli", "muesli"],
    "granola": ["granola"],
    "cornflakes": ["kukurūzas pārslas"],
    "cereal": ["pārslas", "brokastu pārslas"],
    "cereals": ["pārslas", "brokastu pārslas"],
    "buckwheat": ["griķi"],
    "semolina": ["manna"],
    "couscous": ["kuskuss"],
    "bulgur": ["bulgurs"],
    "quinoa": ["kvinoja"],
    # ── meat / poultry ──
    "chicken": ["vista"],
    "beef": ["liellopu gaļa", "liellops"],
    "pork": ["cūkgaļa", "cūkas"],
    "minced": ["malta gaļa"],
    "mince": ["malta gaļa"],
    "sausage": ["desa"],
    "sausages": ["desas"],
    "ham": ["šķiņķis"],
    "bacon": ["bekons"],
    "turkey": ["tītars", "tītara"],
    "lamb": ["jēra gaļa", "jēra"],
    "liver": ["aknas"],
    "steak": ["steiks"],
    "fillet": ["fileja"],
    "ribs": ["ribas", "ribinas"],
    "salami": ["salami", "salāmi"],
    "frankfurter": ["cīsiņi"],
    "wiener": ["cīsiņi", "vīnes"],
    # ── fish ──
    "fish": ["zivis"],
    "salmon": ["lasis"],
    "tuna": ["tuncis"],
    "shrimp": ["garneles"],
    "shrimps": ["garneles"],
    "cod": ["menca"],
    "herring": ["siļķe", "reņģe"],
    "mackerel": ["makrele"],
    "trout": ["forele"],
    "sardines": ["sardīnes"],
    "pangasius": ["pangasius"],
    "squid": ["kalmāri"],
    # ── fruit ──
    "banana": ["banāni"],
    "bananas": ["banāni"],
    "apple": ["āboli"],
    "apples": ["āboli"],
    "orange": ["apelsīni"],
    "oranges": ["apelsīni"],
    "lemon": ["citroni"],
    "lemons": ["citroni"],
    "strawberry": ["zemenes"],
    "strawberries": ["zemenes"],
    "grapes": ["vīnogas"],
    "pear": ["bumbieri"],
    "pears": ["bumbieri"],
    "avocado": ["avokado"],
    "avocados": ["avokado"],
    "avokado": ["avokado"],
    "mango": ["mango"],
    "watermelon": ["arbūzs"],
    "blueberry": ["mellenes"],
    "blueberries": ["mellenes"],
    "raspberry": ["avenes"],
    "raspberries": ["avenes"],
    "cherry": ["ķirši"],
    "cherries": ["ķirši"],
    "peach": ["persiki"],
    "peaches": ["persiki"],
    "plum": ["plūmes"],
    "plums": ["plūmes"],
    "kiwi": ["kivi", "kiwi"],
    "pineapple": ["ananāss", "ananass"],
    "grapefruit": ["greipfrūts", "greipfruts"],
    "lime": ["laimi"],
    "tangerine": ["mandarīni"],
    "mandarin": ["mandarīni"],
    "nectarine": ["nektarīni"],
    "pomegranate": ["granātābols"],
    "melon": ["melone"],
    "coconut": ["kokosrieksts"],
    # ── vegetables ──
    "potatoes": ["kartupeļi"],
    "potato": ["kartupeļi"],
    "tomato": ["tomāti"],
    "tomatoes": ["tomāti"],
    "onion": ["sīpoli"],
    "onions": ["sīpoli"],
    "garlic": ["ķiploki"],
    "carrot": ["burkāni"],
    "carrots": ["burkāni"],
    "cucumber": ["gurķi"],
    "cucumbers": ["gurķi"],
    "pepper": ["pipari"],
    "peppers": ["pipari"],
    "cabbage": ["kāposti"],
    "broccoli": ["brokoļi"],
    "mushroom": ["sēnes"],
    "mushrooms": ["sēnes"],
    "lettuce": ["salāti"],
    "spinach": ["spināti"],
    "corn": ["kukurūza"],
    "zucchini": ["cukini"],
    "beetroot": ["bietes"],
    "beet": ["bietes"],
    "celery": ["selerija"],
    "radish": ["redīsi"],
    "leek": ["puravi"],
    "leeks": ["puravi"],
    "eggplant": ["baklažāni"],
    "aubergine": ["baklažāni"],
    "asparagus": ["sparģeļi"],
    "cauliflower": ["ziedkāposti"],
    "peas": ["zirņi"],
    "dill": ["dilles"],
    "parsley": ["pētersīļi"],
    "basil": ["baziliks"],
    "ginger": ["ingvers"],
    "chili": ["čili"],
    # ── grains / staples ──
    "rice": ["rīsi"],
    "pasta": ["makaroni"],
    "flour": ["milti"],
    "noodles": ["nūdeles", "makaroni"],
    "spaghetti": ["spageti"],
    "penne": ["penne"],
    "lasagna": ["lazanja"],
    "macaroni": ["makaroni"],
    # ── condiments / pantry ──
    "sugar": ["cukurs"],
    "salt": ["sāls"],
    "oil": ["eļļa"],
    "vinegar": ["etiķis"],
    "honey": ["medus"],
    "ketchup": ["kečups"],
    "mustard": ["sinepes"],
    "mayonnaise": ["majonēze"],
    "soy": ["sojas"],
    "sauce": ["mērce"],
    "jam": ["ievārījums"],
    "marmalade": ["marmelāde"],
    "nutella": ["nutella"],
    "peanuts": ["zemesrieksti"],
    "nuts": ["rieksti"],
    "almonds": ["mandeļi"],
    "walnuts": ["valrieksti"],
    "cashew": ["indijas rieksti", "kešju"],
    "raisins": ["rozīnes"],
    "cinnamon": ["kanēlis"],
    "vanilla": ["vaniļa"],
    "yeast": ["raugs"],
    "baking": ["cepšanas"],
    "starch": ["ciete"],
    # ── drinks ──
    "coffee": ["kafija"],
    "tea": ["tēja"],
    "water": ["ūdens"],
    "juice": ["sula"],
    "beer": ["alus"],
    "wine": ["vīns"],
    "soda": ["limonāde", "gāzēts dzēriens"],
    "lemonade": ["limonāde"],
    "cocoa": ["kakao"],
    "smoothie": ["smūtijs"],
    # ── sweets / snacks ──
    "chocolate": ["šokolāde"],
    "cookies": ["cepumi"],
    "biscuits": ["cepumi"],
    "chips": ["čipsi"],
    "crackers": ["krekeri"],
    "candy": ["konfektes"],
    "sweets": ["konfektes", "saldumi"],
    "wafer": ["vafeles"],
    "wafers": ["vafeles"],
    "cake": ["kūka", "torte"],
    "muffin": ["mafins"],
    "popcorn": ["popkorns"],
    "pretzel": ["brēcelis"],
    "marshmallow": ["zefīrs"],
    "gum": ["košļājamā gumija"],
    # ── frozen ──
    "frozen": ["saldēti"],
    "pizza": ["pica"],
    "dumplings": ["pelmeņi"],
    "pierogi": ["pīrāgi", "pīrādziņi"],
    # ── legumes ──
    "lentils": ["lēcas"],
    "lentil": ["lēcas"],
    "lecas": ["lēcas"],
    "beans": ["pupiņas"],
    "chickpeas": ["aunazirņi"],
    "red": ["sarkanas"],
    # ── canned / preserved ──
    "canned": ["konservēti", "konservi"],
    "pickles": ["marinēti gurķi", "skābie gurķi"],
    "olives": ["olīvas"],
    # ── baby / pet ──
    "diapers": ["autiņbiksītes"],
    "nappies": ["autiņbiksītes"],
    "baby": ["bērnu", "mazuļu"],
    "formula": ["maisījums", "bērnu pārtika"],
    "cat": ["kaķu"],
    "dog": ["suņu"],
    "pet": ["mājdzīvnieku"],
    # ── household / non-food ──
    "shampoo": ["šampūns"],
    "toothpaste": ["zobu pasta"],
    "soap": ["ziepes"],
    "detergent": ["mazgāšanas līdzeklis"],
    "bleach": ["balinātājs"],
    "sponge": ["sūklis", "švamme"],
    "trash": ["atkritumu maisi"],
    "garbage": ["atkritumu maisi"],
    "foil": ["folija"],
    "wrap": ["plēve"],
    "napkins": ["salvetes"],
    "tissues": ["salvetes", "kabatas lakatiņi"],
    # ── popular international brand names (same in LV titles) ──
    "ariel": ["ariel"],
    "persil": ["persil"],
    "fairy": ["fairy"],
    "finish": ["finish"],
    "tide": ["tide"],
    "colgate": ["colgate"],
    "oral-b": ["oral-b", "oral b"],
    "gillette": ["gillette"],
    "nivea": ["nivea"],
    "dove": ["dove"],
    "head": ["head"],  # head & shoulders
    "pantene": ["pantene"],
    "pampers": ["pampers"],
    "huggies": ["huggies"],
    "whiskas": ["whiskas"],
    "pedigree": ["pedigree"],
    "danone": ["danone"],
    "activia": ["activia"],
    "president": ["président", "president"],
    "philadelphia": ["philadelphia"],
    "coca-cola": ["coca-cola", "coca cola"],
    "pepsi": ["pepsi"],
    "fanta": ["fanta"],
    "sprite": ["sprite"],
    "redbull": ["red bull"],
    "monster": ["monster"],
    "nescafe": ["nescafé", "nescafe"],
    "jacobs": ["jacobs"],
    "lipton": ["lipton"],
    "barilla": ["barilla"],
    "knorr": ["knorr"],
    "heinz": ["heinz"],
    "kelloggs": ["kellogg's", "kelloggs"],
    "oreo": ["oreo"],
    "lay's": ["lay's", "lays"],
    "pringles": ["pringles"],
    "doritos": ["doritos"],
    "haribo": ["haribo"],
    "milka": ["milka"],
    "lindt": ["lindt"],
    "nutella": ["nutella"],
    "ferrero": ["ferrero"],
    "ritter": ["ritter"],
    "toblerone": ["toblerone"],
    # ── abbreviations / short forms ──
    "avo": ["avocado", "avokado"],

    # ── Latvian: dairy ──
    "piens": ["piens"],
    "piena": ["piens"],
    "pienu": ["piens"],
    "pienam": ["piens"],
    "sviests": ["sviests"],
    "sviesta": ["sviests"],
    "sviestu": ["sviests"],
    "sviestam": ["sviests"],
    "siers": ["siers"],
    "siera": ["siers"],
    "sieru": ["siers"],
    "sieram": ["siers"],
    "sieri": ["siers"],
    "jogurts": ["jogurts"],
    "jogurt": ["jogurts"],
    "jogurta": ["jogurts"],
    "jogurtu": ["jogurts"],
    "jogurti": ["jogurts"],
    "jogurtam": ["jogurts"],
    "biezpiens": ["biezpiens"],
    "biezpiena": ["biezpiens"],
    "biezpienu": ["biezpiens"],
    "krejums": ["krējums"],
    "krejuma": ["krējums"],
    "krejumu": ["krējums"],
    "kefirs": ["kefīrs"],
    "kefira": ["kefīrs"],

    # ── Latvian: cheese varieties ──
    "gouda": ["gouda"],
    "feta": ["feta"],
    "cheddar": ["cheddar", "čedars"],
    "mocarella": ["mocarella", "mozzarella"],
    "parmezans": ["parmezāns"],
    "bri": ["brie", "brī"],
    "kamambera": ["camembert"],
    "kausētais": ["kausētais siers"],
    "kausets": ["kausētais siers"],
    "mascarpone": ["mascarpone"],
    "tilzas": ["tilžas"],
    "tilzites": ["tilzītes"],

    # ── Latvian: eggs ──
    "olas": ["olas"],
    "olu": ["olas"],
    "ola": ["olas"],

    # ── Latvian: bread / bakery ──
    "maize": ["maize"],
    "maizi": ["maize"],
    "maizes": ["maize"],
    "maizite": ["maizīte"],
    "maizites": ["maizītes"],
    "rupjmaize": ["rupjmaize"],
    "rupjmaizi": ["rupjmaize"],
    "rupjmaizes": ["rupjmaize"],
    "baltmaize": ["baltmaize"],
    "tostermaize": ["tostermaize", "toast"],
    "tostermaizi": ["tostermaize", "toast"],
    "tostermaizes": ["tostermaize", "toast"],
    "toastmaize": ["tostermaize", "toast"],
    "pilngraudu": ["pilngraudu"],
    "sausiņi": ["sausiņi", "crispbread"],
    "sausini": ["sausiņi"],
    "bagete": ["bagete"],
    "kruasans": ["kruasāns"],
    "bulcina": ["bulciņa"],
    "bulcinas": ["bulciņas"],

    # ── Latvian: cereals / grains ──
    "griki": ["griķi"],
    "grikis": ["griķi"],
    "griķi": ["griķi"],
    "griku": ["griķi"],
    "auzu": ["auzu pārslas"],
    "parslas": ["pārslas"],
    "putra": ["putra", "auzu pārslas"],
    "putru": ["putra"],
    "musli": ["musli", "muesli"],
    "granola": ["granola"],
    "risi": ["rīsi"],
    "risu": ["rīsi"],
    "risiem": ["rīsi"],
    "makaroni": ["makaroni"],
    "makaronus": ["makaroni"],
    "milti": ["milti"],
    "miltu": ["milti"],
    "miltiem": ["milti"],
    "spageti": ["spageti"],
    "nudeles": ["nūdeles"],
    "kuskuss": ["kuskuss"],
    "bulgurs": ["bulgurs"],
    "kvinoja": ["kvinoja"],
    "manna": ["manna"],

    # ── Latvian: meat / poultry ──
    "vista": ["vista", "vistas"],
    "vistas": ["vista", "vistas"],
    "vistu": ["vista"],
    "vistai": ["vista"],
    "fileja": ["fileja"],
    "fileju": ["fileja"],
    "gala": ["gaļa"],
    "galas": ["gaļa"],
    "galu": ["gaļa"],
    "cukgala": ["cūkgaļa", "cūkas"],
    "cukas": ["cūkas", "cūkgaļa"],
    "liellops": ["liellopa gaļa", "liellops"],
    "liellopa": ["liellopa gaļa"],
    "malta": ["malta gaļa"],
    "maltas": ["malta gaļa"],
    "maltu": ["malta gaļa"],
    "fars": ["farš", "malta gaļa"],
    "farss": ["farš", "malta gaļa"],
    "desa": ["desa"],
    "desas": ["desas", "desa"],
    "desu": ["desa"],
    "desam": ["desa"],
    "cisini": ["cīsiņi"],
    "cisiniem": ["cīsiņi"],
    "cisinus": ["cīsiņi"],
    "skinki": ["šķiņķis"],
    "skinkis": ["šķiņķis"],
    "bekons": ["bekons"],
    "bekona": ["bekons"],
    "salami": ["salami", "salāmi"],
    "titars": ["tītars"],
    "titara": ["tītara"],
    "jera": ["jēra gaļa"],
    "aknas": ["aknas"],
    "steiks": ["steiks"],
    "karbonades": ["karbonādes"],
    "karbonade": ["karbonāde"],

    # ── Latvian: fish ──
    "zivis": ["zivis"],
    "zivs": ["zivis"],
    "zivju": ["zivis"],
    "zivi": ["zivis"],
    "lasis": ["lasis"],
    "lasa": ["lasis"],
    "lasim": ["lasis"],
    "tuncis": ["tuncis"],
    "tunca": ["tuncis"],
    "menca": ["menca"],
    "silke": ["siļķe"],
    "renge": ["reņģe"],
    "makrele": ["makrele"],
    "forele": ["forele"],
    "garneles": ["garneles"],
    "garnelem": ["garneles"],
    "kalmari": ["kalmāri"],

    # ── Latvian: fruit ──
    "banani": ["banāni"],
    "bananus": ["banāni"],
    "bananu": ["banāni"],
    "aboli": ["āboli"],
    "abolus": ["āboli"],
    "abolu": ["āboli"],
    "apelsini": ["apelsīni"],
    "apelsinus": ["apelsīni"],
    "citroni": ["citroni"],
    "citronus": ["citroni"],
    "zemenes": ["zemenes"],
    "zemenem": ["zemenes"],
    "zemenu": ["zemenes"],
    "vinogas": ["vīnogas"],
    "vinogu": ["vīnogas"],
    "bumbieri": ["bumbieri"],
    "bumbieru": ["bumbieri"],
    "avokado": ["avokado"],
    "mellenes": ["mellenes"],
    "mellenu": ["mellenes"],
    "avenes": ["avenes"],
    "avenu": ["avenes"],
    "kirsi": ["ķirši"],
    "kirsu": ["ķirši"],
    "persiki": ["persiki"],
    "persiku": ["persiki"],
    "plumes": ["plūmes"],
    "plumu": ["plūmes"],
    "kivi": ["kivi", "kiwi"],
    "ananass": ["ananāss"],
    "arbuzs": ["arbūzs"],
    "mandarini": ["mandarīni"],
    "mandarinu": ["mandarīni"],
    "melone": ["melone"],
    "melones": ["melone"],

    # ── Latvian: vegetables ──
    "kartupeli": ["kartupeļi"],
    "kartupelus": ["kartupeļi"],
    "kartupelu": ["kartupeļi"],
    "tomati": ["tomāti"],
    "tomatus": ["tomāti"],
    "tomatu": ["tomāti"],
    "sipoli": ["sīpoli"],
    "sipolus": ["sīpoli"],
    "sipolu": ["sīpoli"],
    "kiploki": ["ķiploki"],
    "kiploku": ["ķiploki"],
    "burkani": ["burkāni"],
    "burkanus": ["burkāni"],
    "burkanu": ["burkāni"],
    "gurki": ["gurķi"],
    "gurkus": ["gurķi"],
    "gurku": ["gurķi"],
    "pipari": ["pipari"],
    "piparus": ["pipari"],
    "kaposti": ["kāposti"],
    "kapostus": ["kāposti"],
    "kapostu": ["kāposti"],
    "brokoli": ["brokoļi"],
    "senes": ["sēnes"],
    "senu": ["sēnes"],
    "senem": ["sēnes"],
    "salati": ["salāti"],
    "salatu": ["salāti"],
    "spinati": ["spināti"],
    "spinatu": ["spināti"],
    "kukuruza": ["kukurūza"],
    "kukuruzas": ["kukurūza"],
    "cukini": ["cukini"],
    "bietes": ["bietes"],
    "biesu": ["bietes"],
    "selerija": ["selerija"],
    "redisi": ["redīsi"],
    "puravi": ["puravi"],
    "baklazani": ["baklažāni"],
    "spargelis": ["sparģeļi"],
    "ziedkaposti": ["ziedkāposti"],
    "zirni": ["zirņi"],
    "zirnus": ["zirņi"],
    "zirnu": ["zirņi"],
    "dilles": ["dilles"],
    "petersili": ["pētersīļi"],
    "ingvers": ["ingvers"],
    "cili": ["čili"],

    # ── Latvian: condiments / pantry ──
    "cukurs": ["cukurs"],
    "cukura": ["cukurs"],
    "cukuru": ["cukurs"],
    "sals": ["sāls"],
    "sala": ["sāls"],
    "salij": ["sāls"],
    "ella": ["eļļa"],
    "ellas": ["eļļa"],
    "ellu": ["eļļa"],
    "olivella": ["olīveļļa", "eļļa"],
    "saulespuku": ["saulespuķu eļļa"],
    "etikis": ["etiķis"],
    "medus": ["medus"],
    "medu": ["medus"],
    "medum": ["medus"],
    "kecups": ["kečups"],
    "sinepes": ["sinepes"],
    "majoneze": ["majonēze"],
    "sojas": ["sojas"],
    "merce": ["mērce"],
    "merci": ["mērce"],
    "merces": ["mērce"],
    "ievarijums": ["ievārījums"],
    "rieksti": ["rieksti"],
    "riekstus": ["rieksti"],
    "riekstu": ["rieksti"],
    "zemesrieksti": ["zemesrieksti"],
    "zemesriekstu": ["zemesrieksti"],
    "mandeli": ["mandeļi"],
    "mandelu": ["mandeļi"],
    "valrieksti": ["valrieksti"],
    "rozines": ["rozīnes"],
    "kanelis": ["kanēlis"],
    "vanila": ["vaniļa"],
    "raugs": ["raugs"],

    # ── Latvian: drinks ──
    "kafija": ["kafija"],
    "kafijas": ["kafija"],
    "kafiju": ["kafija"],
    "teja": ["tēja"],
    "tejas": ["tēja"],
    "teju": ["tēja"],
    "udens": ["ūdens"],
    "udeni": ["ūdens"],
    "udenim": ["ūdens"],
    "sula": ["sula"],
    "sulu": ["sula"],
    "sulai": ["sula"],
    "alus": ["alus"],
    "alu": ["alus"],
    "alum": ["alus"],
    "vins": ["vīns"],
    "vina": ["vīns"],
    "vinu": ["vīns"],
    "limonade": ["limonāde"],
    "kakao": ["kakao"],

    # ── Latvian: sweets / snacks ──
    "sokolade": ["šokolāde"],
    "sokolades": ["šokolāde"],
    "sokoladi": ["šokolāde"],
    "cepumi": ["cepumi"],
    "cepumu": ["cepumi"],
    "cepumiem": ["cepumi"],
    "cipsi": ["čipsi"],
    "cipsus": ["čipsi"],
    "cipsu": ["čipsi"],
    "konfektes": ["konfektes"],
    "konfeksu": ["konfektes"],
    "saldumi": ["saldumi"],
    "saldumu": ["saldumi"],
    "vafeles": ["vafeles"],
    "kuka": ["kūka"],
    "kukas": ["kūka"],
    "kuku": ["kūka"],
    "torte": ["torte"],
    "torti": ["torte"],
    "saldejums": ["saldējums"],
    "saldejuma": ["saldējums"],
    "saldejumu": ["saldējums"],

    # ── Latvian: frozen / prepared ──
    "saldeti": ["saldēti"],
    "saldetu": ["saldēti"],
    "pica": ["pica"],
    "picu": ["pica"],
    "picai": ["pica"],
    "pelmeni": ["pelmeņi"],
    "pelmenus": ["pelmeņi"],
    "pelmenu": ["pelmeņi"],
    "piragi": ["pīrāgi"],
    "piragus": ["pīrāgi"],
    "piragu": ["pīrāgi"],
    "piradziņi": ["pīrādziņi"],

    # ── Latvian: legumes ──
    "lecas": ["lēcas"],
    "lecu": ["lēcas"],
    "lecam": ["lēcas"],
    "pupinas": ["pupiņas"],
    "pupinu": ["pupiņas"],
    "aunazirni": ["aunazirņi"],

    # ── Latvian: household ──
    "sampuns": ["šampūns"],
    "sampuna": ["šampūns"],
    "sampunu": ["šampūns"],
    "ziepes": ["ziepes"],
    "ziepju": ["ziepes"],
    "zobu": ["zobu pasta"],
    "velas": ["veļas"],
    "pulveris": ["pulveris", "veļas pulveris"],
    "tualetes": ["tualetes papīrs"],
    "papirs": ["papīrs", "tualetes papīrs"],
    "trauku": ["trauku mazgāšanas līdzeklis"],
    "salvetes": ["salvetes"],
    "folija": ["folija"],
    "pleve": ["plēve"],
    "autinbiksites": ["autiņbiksītes"],
    "mikstinatajs": ["mīkstinātājs"],
}


def expand_query_for_search(query: str) -> str:
    """Expand query terms with synonyms (EN→LV, LV→LV, inflections).

    Runs phrase expansion first (e.g. "zobu pasta" → "toothpaste").
    Tokens consumed by a matched phrase are NOT expanded again individually,
    preventing false positives like "pasta" → "makaroni" inside "zobu pasta".
    """
    if not (query or "").strip():
        return query
    q_norm = normalize_text(query)
    extra: list[str] = []
    consumed_tokens: set[str] = set()

    for phrase, syns in PHRASE_SYNONYMS.items():
        pn = normalize_text(phrase)
        if pn in q_norm:
            extra.extend(syns)
            consumed_tokens.update(pn.split())

    tokens = tokenize(query)
    for t in tokens:
        if t in consumed_tokens:
            continue
        syns = search_synonyms.get(t)
        if syns:
            extra.extend(syns)
    if not extra:
        return query
    return query.strip() + " " + " ".join(extra)


def get_search_suggestions(query: str) -> list[str]:
    """Return suggested alternative search terms when no results (e.g. avocado -> avokado)."""
    if not (query or "").strip():
        return []
    tokens = tokenize(query)
    out: list[str] = []
    seen: set[str] = set()
    for t in tokens:
        syns = search_synonyms.get(t)
        if syns:
            for s in syns:
                if s not in seen and s != t:
                    seen.add(s)
                    out.append(s)
    return out[:5]
